In [21]:
import gym
import numpy as np
import random
from IPython.display import clear_output

In [22]:
env = gym.make('Marvin-v0')
action_space_size = env.action_space.shape[0]
state_space_size = env.observation_space.shape[0]

q_table = np.zeros((state_space_size, action_space_size))

In [23]:
print(action_space_size)
print(state_space_size)
print(q_table)

4
24
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [24]:
num_episodes = 1000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [25]:
rewards_all_episodes = []

#Q-learning algorithm
for episode in range(num_episodes):
    state = env.reset()
    
    done = False
    rewards_current_episode = 0
    print("initial state = ", state)
    
    for step in range(max_steps_per_episode):
        # Exploration-Explotation trade off
        exploration_rate_treshold = random.uniform(0,1)
        if exploration_rate_treshold >= exploration_rate:
            action = np.argmax(q_table[state, :])
        else:
            action = env.action_space.sample()
        
        print("action = ", action)
        new_state, reward, done, info = env.step(action)
        
        # Update Q-table
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
            learning_rate * (reward  + discount_rate * np.max(q_table[state, :]))
        state = new_state
        rewards_current_episode += reward
        if done == True:
            break
            
    #Exploration decay logic 
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)
    rewards_all_episodes.append(rewards_current_episode)

#Calculate and print the average reward per 1000 episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes / 1000)
count = 1000
print("*** Average reward per 1000 episodes ***\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/ 1000)))
    count += 1000
    

#Print updated Q-table
print("\n\n*****Q-table*****\n\n")
print(q_table)

initial state =  [-1.42626809e-02  3.14135896e-05 -2.66309112e-03 -1.59984541e-02
  8.76187086e-02  5.68352127e-03  9.34906855e-01 -4.07106088e-03
  0.00000000e+00  5.81831448e-02  5.74575737e-03  8.44461292e-01
 -4.20111418e-03  0.00000000e+00  6.56925142e-01  6.64385498e-01
  6.87637448e-01  7.29554415e-01  7.95949161e-01  8.97820354e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00]
action =  [-0.64798945  0.06785727 -0.23356023  0.56432784]


IndexError: arrays used as indices must be of integer (or boolean) type