In [1]:
import gym
import numpy as np
import random
from IPython.display import clear_output

In [2]:
env = gym.make('Marvin-v0')
action_space_size = env.action_space.shape[0]
state_space_size = env.observation_space.shape[0]

q_table = np.zeros((state_space_size, action_space_size))
print(action_space_size)
print(env.action_space)
print(env.action_space.high)
print(env.action_space.low)
print(state_space_size)
print(env.observation_space)
print(env.observation_space.high)
print(env.observation_space.low)
print(q_table)

4
Box(4,)
[1. 1. 1. 1.]
[-1. -1. -1. -1.]
24
Box(24,)
[inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
 inf inf inf inf inf inf]
[-inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
 -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
import random, math
random.seed(422142)

def mult_and_sum(a, b):
    result = 0
    for i in range(len(a)):
        result += a[i] * b[i]
    return result

def l_plus_c(a, c):
    result = []
    for i in range(len(a)):
        res = a[i] + c
        result.append(res)
    return result

class Neuron(object):
    def __init__(self, inputs_count):
        self.w = [random.random()] * inputs_count
        self.bias = random.random()
        
    def __str__(self):
        return [self.w, self.bias]
        
    def _net_input(self, data):
        return mult_and_sum(self.w, data) + self.bias
    
    def _activation_function(self, observation):
        net_input = self._net_input(observation)
        return 1 / (1 + math.exp(-(net_input)))
        
    # Returning 1 single number
    def predict(self, data):
        result = self._activation_function(data)
        return ((result - 0.5) * 2 if result >= 0.5 else (-result * 2))

    
    
    def accuracy(self, data, target):
        result = 0
        for X, y in zip(data, target):
            result += int(self.predict(X) == y)
        return result / len(target)    
    
    def learn(self, observation, reward, eta = 0.001):
        data = np.array(observation)
        e = eta * (reward - self.predict(data))
        self.w += data * e
        self.bias += e
        return

In [4]:
# create a network of three layers. Input -> 24 Neurons accept all features produces 1 single number each
# Second layer is consist of 24 Neurons as well -> we are sending results from first layer 
#                                                                to each neuron in second layer
# Third layer is consist of 4 Neurons. Each accepts all answers from Second layer and return 1 single number.
#                                                            Collection of thouse numbers is my action


In [5]:
class Layer(object):
    def __init__(self, input_counts):
        self.neurons = []
        self.previousLayer = None
        self.nextLayer = None
        
        for i in range(input_counts):
            self.neurons.append(Neuron(input_counts))
    
    def connectPrevious(self, previousLayer):
        self.previousLayer = previousLayer
    
    def connectTo(self, nextLayer):
        self.nextLayer = nextLayer
        nextLayer.connectPrevious(self)
    
    
    def run(self, observation):
        # Run through each Neuron and command them to make a prediction from given observation. 
        # return array of results
        result = []
        for neuron in self.neurons:
            result.append(neuron.predict(observation))
        return result
    
    
    def update(self, oldObservation, reward):
        # Run through each Neuron and command them to learn from data!
        for neuron in self.neurons:
            neuron.learn(oldObservation, reward)
    
    def howManyNeurons(self):
        return len(self.neurons)
        
    def printConnectedLayers(self):
        print(self.previousLayer)
        print(self.nextLayer)
    

In [6]:
l = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(l)
print(l[0])
print(l[-1])
print(l[1:-1])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
0
9
[1, 2, 3, 4, 5, 6, 7, 8]


In [7]:
class Brain(object):
    def __init__(self, numberOfLayers, input_counts, output_counts):
        self.layers = []
        self.outputLayerW = [random.random()] * input_counts
        self.initializeLayers(numberOfLayers, input_counts, output_counts)
        
    def initializeLayers(self, quantity, neuronPerLayer, neuronPerOutput):
        for i in range (quantity):
            # Create quantity - 1 layers each with neuronPerLayer neurons 
            # Connect each layer
            freshLayer = Layer(neuronPerLayer) if i != quantity - 1 else Layer(neuronPerOutput)
            if (i != 0):    
                self.layers[-1].connectTo(freshLayer)
            self.layers.append(freshLayer)
    
    
    def learn(self, oldObservation, reward):
        # Run through each layer and command them to update!
        # I wish! Second layer should get data from first layer! 
        
        # Input layer
        input_layer = self.layers[0]
        
        # Hidden Layers 
        hidden_layers = self.layers[1: -1]
        
        # Output layer
        output_layer = self.layers[-1]
        
        # Comand the first layer to update himself
        input_layer.update(oldObservation, reward)
        
        # Update hidden Layers in a loop
        # run the layer to get new results
        results_for_hiddenLayer = input_layer.run(oldObservation)
        for hiddenLayer in hidden_layers:
                hiddenLayer.update(results_for_hiddenLayer, reward)
                results_for_hiddenLayer = hiddenLayer.run(results_for_hiddenLayer)

        # Get results from last hidden layer and use it to update the outputLayer
        
        results_for_outputLayer = results_for_hiddenLayer
        print("results for output! ", results_for_outputLayer)
        
        
    
    def chooseAction(self, observation):
        layer_output = []
        for layer in self.layers:
            # Run though each layer and command them to return array of all answers from all neurons in the layer
            layer_output.append(layer.run(observation))
    
    
    
    def howManyLayers(self):
        return len(self.layers)
    
    def getLayers(self):
        return self.layers

In [8]:
marvin = Brain(3, 24, 4)
print(marvin.howManyLayers())
layers = marvin.getLayers()
for layer in layers:
    print(layer.howManyNeurons())

3
24
24
4


In [9]:
# Next we integrate this nn in our enviroment. allow agent choose an action!

num_episodes = 10
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001




In [10]:
rewards_all_episodes = []



for episode in range(num_episodes):
    observation = env.reset()
    done = False
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode):
         # Exploration-Explotation trade off
        env.render()
        exploration_rate_treshold = random.uniform(0,1)
        if exploration_rate_treshold >= exploration_rate:
            action = marvin.chooseAction(observation)
        else:
            action = env.action_space.sample()

        new_observation, reward, done, info = env.step(action)
        print(observation, reward, done, info)
        # Update my weights according to reward on each neuron in my brain.
        marvin.learn(observation, reward)
        rewards_current_episode += reward
        if done == True:
            break
        
    #Exploration decay logic 
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)
    rewards_all_episodes.append(rewards_current_episode) 


[-1.42792333e-02 -4.67989920e-05  1.73622999e-03 -1.59917605e-02
  8.70858878e-02 -1.87642453e-03  9.34906870e-01  0.00000000e+00
  0.00000000e+00  5.72824292e-02 -1.87134231e-03  8.45454082e-01
 -7.76102146e-10  0.00000000e+00  6.56928718e-01  6.64389133e-01
  6.87641203e-01  7.29558408e-01  7.95953512e-01  8.97825241e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] -0.0314735995605588 False {}
results for output!  [0.9999997976110233, 0.9999999989551043, 0.9999999536599586, 0.9999999049006725, 0.9979866119214214, 0.9999998237748806, 0.9999998948444622, 0.642453924680858, 0.9999992883796178, 0.9982194637012503, 0.8509368693027006, 0.9998653027096274, 0.9999999802487125, 0.9999812388259821, 0.9998232447827298, 0.9999297613821545, 0.9999999912414745, 0.9999999423765285, 0.9999486156399362, 0.9964516787976312, 0.9999098521298251, 0.9996167534414744, 0.8872749952736496, 0.9999999970418303]
[-1.42792333e-02 -4.67989920e-05  1.73622999e-03 -1.59917605e-02
  8.70858878e-

[-1.42792333e-02 -4.67989920e-05  1.73622999e-03 -1.59917605e-02
  8.70858878e-02 -1.87642453e-03  9.34906870e-01  0.00000000e+00
  0.00000000e+00  5.72824292e-02 -1.87134231e-03  8.45454082e-01
 -7.76102146e-10  0.00000000e+00  6.56928718e-01  6.64389133e-01
  6.87641203e-01  7.29558408e-01  7.95953512e-01  8.97825241e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] -0.043804174207773 False {}
results for output!  [0.9999997220704921, 0.9999999985254715, 0.9999999360808871, 0.9999998692959804, 0.9973848702420491, 0.999999758751507, 0.9999998550438216, 0.5975956507793165, 0.9999990305879627, 0.9976905118031894, 0.8212287586239406, 0.999822200047725, 0.9999999725645119, 0.9999749444281503, 0.999767107859596, 0.9999071353403681, 0.9999999877715244, 0.9999999205853349, 0.999931735836205, 0.9954142246996567, 0.9998806560882934, 0.9994990135167987, 0.8628504093116207, 0.9999999958440475]
[-1.42792333e-02 -4.67989920e-05  1.73622999e-03 -1.59917605e-02
  8.70858878e-02 -

[-1.42792333e-02 -4.67989920e-05  1.73622999e-03 -1.59917605e-02
  8.70858878e-02 -1.87642453e-03  9.34906870e-01  0.00000000e+00
  0.00000000e+00  5.72824292e-02 -1.87134231e-03  8.45454082e-01
 -7.76102146e-10  0.00000000e+00  6.56928718e-01  6.64389133e-01
  6.87641203e-01  7.29558408e-01  7.95953512e-01  8.97825241e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] -0.156825319859512 False {}
results for output!  [0.9999995224834357, 0.9999999973408555, 0.9999998893097466, 0.9999997751000844, 0.9959323651208949, 0.9999995877917678, 0.9999997492529458, 0.5211145267287356, 0.9999983580430036, 0.996416368491952, 0.7624544429116737, 0.9997152678722925, 0.9999999518938159, 0.9999590325575314, 0.9996282507496166, 0.9998508543732707, 0.9999999783621394, 0.9999998626855624, 0.9998894227981996, 0.9929328563243072, 0.9998078804419404, 0.9992115158237744, 0.8127366246906564, 0.9999999925642742]
[-1.42792333e-02 -4.67989920e-05  1.73622999e-03 -1.59917605e-02
  8.70858878e-0

[-1.42792333e-02 -4.67989920e-05  1.73622999e-03 -1.59917605e-02
  8.70858878e-02 -1.87642453e-03  9.34906870e-01  0.00000000e+00
  0.00000000e+00  5.72824292e-02 -1.87134231e-03  8.45454082e-01
 -7.76102146e-10  0.00000000e+00  6.56928718e-01  6.64389133e-01
  6.87641203e-01  7.29558408e-01  7.95953512e-01  8.97825241e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] -0.009913321280229898 False {}
results for output!  [0.9999993503212168, 0.999999996278135, 0.9999998487053148, 0.9999996937487412, 0.994780937283624, 0.9999994409874491, 0.9999996574929417, 0.47950290990418054, 0.9999977846423775, 0.9954081554347964, 0.7251076148309223, 0.9996282443649087, 0.9999999337660639, 0.9999458553900462, 0.9995155573476393, 0.9998049380440568, 0.9999999700492643, 0.9999998124822189, 0.9998546544046738, 0.990983838607489, 0.9997483927240889, 0.9989809838343018, 0.7796191156103134, 0.9999999896406733]
[-1.42792333e-02 -4.67989920e-05  1.73622999e-03 -1.59917605e-02
  8.70858878e

[-1.42792333e-02 -4.67989920e-05  1.73622999e-03 -1.59917605e-02
  8.70858878e-02 -1.87642453e-03  9.34906870e-01  0.00000000e+00
  0.00000000e+00  5.72824292e-02 -1.87134231e-03  8.45454082e-01
 -7.76102146e-10  0.00000000e+00  6.56928718e-01  6.64389133e-01
  6.87641203e-01  7.29558408e-01  7.95953512e-01  8.97825241e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] -0.009485327581565773 False {}
results for output!  [0.9999991179621808, 0.9999999947993028, 0.9999997936286182, 0.9999995838489091, 0.9933267960294008, 0.9999992435478642, 0.999999533114847, 0.43994887666659555, 0.9999970177503046, 0.9941365436973877, 0.6858124541463295, 0.9995159977312436, 0.999999908982651, 0.9999286261417017, 0.9993705142849565, 0.9997455972381353, 0.9999999586188109, 0.9999997444512359, 0.999809470162994, 0.9885411673178228, 0.9996713983891445, 0.99868706328283, 0.7437405216740827, 0.999999985592499]
[-1.42792333e-02 -4.67989920e-05  1.73622999e-03 -1.59917605e-02
  8.70858878e-02

[-1.42792333e-02 -4.67989920e-05  1.73622999e-03 -1.59917605e-02
  8.70858878e-02 -1.87642453e-03  9.34906870e-01  0.00000000e+00
  0.00000000e+00  5.72824292e-02 -1.87134231e-03  8.45454082e-01
 -7.76102146e-10  0.00000000e+00  6.56928718e-01  6.64389133e-01
  6.87641203e-01  7.29558408e-01  7.95953512e-01  8.97825241e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] -0.017961891094844733 False {}
results for output!  [0.9999988075097437, 0.9999999927620342, 0.9999997196719235, 0.999999436873944, 0.9915103652434758, 0.9999989806767791, 0.9999993662175506, 0.40325883635758153, 0.9999960023835777, 0.9925499955062878, 0.6455896633750786, 0.9993726781116787, 0.9999998754400623, 0.9999063251583811, 0.9991857220975928, 0.9996696785107977, 0.9999999430592614, 0.9999996531880291, 0.9997513404284286, 0.9855149757143942, 0.9995727493103084, 0.9983161391529694, 0.7059104394840103, 0.999999980043355]
[-1.42792333e-02 -4.67989920e-05  1.73622999e-03 -1.59917605e-02
  8.70858878

[-1.42792333e-02 -4.67989920e-05  1.73622999e-03 -1.59917605e-02
  8.70858878e-02 -1.87642453e-03  9.34906870e-01  0.00000000e+00
  0.00000000e+00  5.72824292e-02 -1.87134231e-03  8.45454082e-01
 -7.76102146e-10  0.00000000e+00  6.56928718e-01  6.64389133e-01
  6.87641203e-01  7.29558408e-01  7.95953512e-01  8.97825241e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] -0.0005401088396720013 False {}
results for output!  [0.9999984352918638, 0.9999999902457204, 0.9999996305685317, 0.9999992604956176, 0.9894726790672692, 0.9999986665830458, 0.9999991652757856, 0.371908254859906, 0.9999947957275632, 0.9907720777845881, 0.6085143341512687, 0.9992082936317319, 0.9999998347167396, 0.9998804016142815, 0.9989742245080491, 0.9995824292319888, 0.9999999240629085, 0.9999995433371764, 0.9996841702658157, 0.982149147023565, 0.9994592153207436, 0.9978955808041914, 0.6701199204579502, 0.9999999732224167]
[-1.42792333e-02 -4.67989920e-05  1.73622999e-03 -1.59917605e-02
  8.70858878

[-1.42792333e-02 -4.67989920e-05  1.73622999e-03 -1.59917605e-02
  8.70858878e-02 -1.87642453e-03  9.34906870e-01  0.00000000e+00
  0.00000000e+00  5.72824292e-02 -1.87134231e-03  8.45454082e-01
 -7.76102146e-10  0.00000000e+00  6.56928718e-01  6.64389133e-01
  6.87641203e-01  7.29558408e-01  7.95953512e-01  8.97825241e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] -0.0076633423566818265 False {}
results for output!  [0.9999978902899151, 0.9999999864487936, 0.9999994994597694, 0.99999900200198, 0.9866860009767588, 0.999998208272667, 0.9999988698089926, 0.3398449337206002, 0.9999930446489584, 0.9883427942708076, 0.5675657727435288, 0.9989781361737164, 0.9999997743291609, 0.9998436102633195, 0.9986787510918265, 0.9994600209226427, 0.9999998957339895, 0.9999993818539084, 0.9995894139616548, 0.9775894738804027, 0.9992997046669425, 0.9973136333883343, 0.6295423550794981, 0.9999999629803964]
[-1.42792333e-02 -4.67989920e-05  1.73622999e-03 -1.59917605e-02
  8.70858878e

[-1.42792333e-02 -4.67989920e-05  1.73622999e-03 -1.59917605e-02
  8.70858878e-02 -1.87642453e-03  9.34906870e-01  0.00000000e+00
  0.00000000e+00  5.72824292e-02 -1.87134231e-03  8.45454082e-01
 -7.76102146e-10  0.00000000e+00  6.56928718e-01  6.64389133e-01
  6.87641203e-01  7.29558408e-01  7.95953512e-01  8.97825241e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] 0.024458622654277885 False {}
results for output!  [0.9999972694110868, 0.9999999819998131, 0.9999993494107036, 0.999998707264633, 0.9837118404688305, 0.9999976878326637, 0.9999985318755287, 0.31543987302561827, 0.9999910662994578, 0.9857514060534034, 0.5330990729738849, 0.9987266262877665, 0.9999997047156075, 0.9998028940574, 0.9983565316998941, 0.9993259940646189, 0.9999998629038487, 0.9999991972064246, 0.9994851359804096, 0.9727718241946703, 0.9991248313755388, 0.9966846967530434, 0.5943910080259924, 0.9999999510344437]
[-1.42792333e-02 -4.67989920e-05  1.73622999e-03 -1.59917605e-02
  8.70858878e-0

[-1.42792333e-02 -4.67989920e-05  1.73622999e-03 -1.59917605e-02
  8.70858878e-02 -1.87642453e-03  9.34906870e-01  0.00000000e+00
  0.00000000e+00  5.72824292e-02 -1.87134231e-03  8.45454082e-01
 -7.76102146e-10  0.00000000e+00  6.56928718e-01  6.64389133e-01
  6.87641203e-01  7.29558408e-01  7.95953512e-01  8.97825241e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] -0.3626537753691264 False {}
results for output!  [0.9999963620648313, 0.9999999753015134, 0.9999991290585055, 0.999998276141004, 0.979662789995853, 0.9999969298673965, 0.9999980359472223, 0.2898557797361099, 0.9999882006571181, 0.9822252351629299, 0.4953305051651744, 0.9983751504103493, 0.9999996016975989, 0.9997452091364682, 0.997907255853518, 0.9991382931870554, 0.9999998140472686, 0.9999989263009201, 0.9993382932601369, 0.9662858731416404, 0.9988795912233193, 0.995816352445982, 0.5550932627131404, 0.9999999331357294]
[-1.42792333e-02 -4.67989920e-05  1.73622999e-03 -1.59917605e-02
  8.70858878e-02 

[-1.42620830e-02  3.55490437e-05 -3.01366076e-03 -1.59982514e-02
  8.76632482e-02  6.43171603e-03  9.34906706e-01 -4.60700101e-03
  0.00000000e+00  5.82634844e-02  6.50211098e-03  8.44363853e-01
 -4.75411396e-03  0.00000000e+00  6.56924963e-01  6.64385319e-01
  6.87637269e-01  7.29554236e-01  7.95948982e-01  8.97820115e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] -0.03567755926648894 False {}
results for output!  [0.999993529202881, 0.9999999531359707, 0.9999984344670281, 0.9999969276700871, 0.9686782110682552, 0.9999945792955811, 0.9999964747799992, 0.23079202516422215, 0.9999794086212774, 0.9726717134957297, 0.4156906763172006, 0.9973714112018561, 0.999999272046115, 0.9995758652493558, 0.9966300366966452, 0.9985999415226448, 0.9999996559918065, 0.9999980739348913, 0.9989124345472002, 0.9490539223154186, 0.9981742538869716, 0.993396386290847, 0.4718732522573952, 0.9999998744608953]
[-1.42620830e-02  3.55490437e-05 -3.01366076e-03 -1.59982514e-02
  8.76632482e-

[-1.42620830e-02  3.55490437e-05 -3.01366076e-03 -1.59982514e-02
  8.76632482e-02  6.43171603e-03  9.34906706e-01 -4.60700101e-03
  0.00000000e+00  5.82634844e-02  6.50211098e-03  8.44363853e-01
 -4.75411396e-03  0.00000000e+00  6.56924963e-01  6.64385319e-01
  6.87637269e-01  7.29554236e-01  7.95948982e-01  8.97820115e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] -0.04393074882030487 False {}
results for output!  [0.9999914062988862, 0.999999935730169, 0.9999979099545124, 0.9999959156832539, 0.9613788517935549, 0.9999928272410075, 0.999995297145184, 0.20742239764989145, 0.999972910833171, 0.9663199634012629, 0.3801374990805082, 0.9966706074905092, 0.999999020096014, 0.9994549877858119, 0.9957416301985003, 0.9982226474043936, 0.9999995341249333, 0.9999974312323252, 0.9986113882408982, 0.9378596596278654, 0.9976789572816909, 0.9917403173468133, 0.4333959513412733, 0.9999998287349197]
[-1.42620830e-02  3.55490437e-05 -3.01366076e-03 -1.59982514e-02
  8.76632482e-0

[-1.42620830e-02  3.55490437e-05 -3.01366076e-03 -1.59982514e-02
  8.76632482e-02  6.43171603e-03  9.34906706e-01 -4.60700101e-03
  0.00000000e+00  5.82634844e-02  6.50211098e-03  8.44363853e-01
 -4.75411396e-03  0.00000000e+00  6.56924963e-01  6.64385319e-01
  6.87637269e-01  7.29554236e-01  7.95948982e-01  8.97820115e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] -0.016532316883403862 False {}
results for output!  [0.9999854481878705, 0.9999998844992852, 0.9999964264361787, 0.9999930712974998, 0.9434087304735506, 0.9999879364966953, 0.9999919699641158, 0.17452242405024787, 0.9999549276135338, 0.9506501498840911, 0.32283892010859816, 0.994839967765107, 0.9999982987253657, 0.9991319328280066, 0.9934302249635194, 0.9972328581126169, 0.9999991820682079, 0.999995616147749, 0.9978147537850426, 0.9110643801369169, 0.9963773446758584, 0.9875054204303992, 0.36927903776064586, 0.9999996951924073]
[-1.42620830e-02  3.55490437e-05 -3.01366076e-03 -1.59982514e-02
  8.766324

[-1.42620830e-02  3.55490437e-05 -3.01366076e-03 -1.59982514e-02
  8.76632482e-02  6.43171603e-03  9.34906706e-01 -4.60700101e-03
  0.00000000e+00  5.82634844e-02  6.50211098e-03  8.44363853e-01
 -4.75411396e-03  0.00000000e+00  6.56924963e-01  6.64385319e-01
  6.87637269e-01  7.29554236e-01  7.95948982e-01  8.97820115e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] 0.019658158212900158 False {}
results for output!  [0.9999811137611436, 0.9999998455087185, 0.9999953391772525, 0.9999909991460567, 0.931979155730692, 0.9999843970125832, 0.9999895340295479, 0.16030705050221994, 0.9999420202133413, 0.9406577261986018, 0.2971024585112154, 0.9935992498850132, 0.9999977638455371, 0.9989078539574607, 0.9918701586446013, 0.9965589833822026, 0.9999989188030836, 0.9999942877895689, 0.9972676628060326, 0.8945212126370825, 0.995489732145104, 0.9846977307381433, 0.33999804483821605, 0.9999995942980993]
[-1.42620830e-02  3.55490437e-05 -3.01366076e-03 -1.59982514e-02
  8.76632482

[-1.42620830e-02  3.55490437e-05 -3.01366076e-03 -1.59982514e-02
  8.76632482e-02  6.43171603e-03  9.34906706e-01 -4.60700101e-03
  0.00000000e+00  5.82634844e-02  6.50211098e-03  8.44363853e-01
 -4.75411396e-03  0.00000000e+00  6.56924963e-01  6.64385319e-01
  6.87637269e-01  7.29554236e-01  7.95948982e-01  8.97820115e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] 0.05929542162020882 False {}
results for output!  [0.9999749449706747, 0.9999997881844462, 0.9999937835449999, 0.9999880470718936, 0.9173184935880341, 0.9999793782827902, 0.9999860513315066, 0.1471594959730489, 0.9999238263995256, 0.9278021434030395, 0.27182153573791656, 0.991921637853683, 0.9999969921214233, 0.9985996262040133, 0.9897674475924658, 0.9956444729180265, 0.9999985366385138, 0.9999923891463656, 0.9965205924563272, 0.8738172145995302, 0.9942840084864073, 0.9809643171731468, 0.3108036950009534, 0.9999994467457196]
[-1.42620830e-02  3.55490437e-05 -3.01366076e-03 -1.59982514e-02
  8.76632482e

results for output!  [0.9999682257992017, 0.9999997239548422, 0.9999920813220478, 0.9999848288079596, 0.9029014488303941, 0.9999739292578271, 0.9999822429144902, 0.13979216612263223, 0.999904173040465, 0.9151044512440336, 0.25421229245981647, 0.9901748058405486, 0.9999961415283796, 0.998273604618493, 0.987584682889386, 0.9946886004166517, 0.9999981131726374, 0.9999903134343842, 0.9957355515135955, 0.8540046327504638, 0.9930231085011976, 0.97713826386399, 0.28979133991333383, 0.9999992821840045]
[-1.42620830e-02  3.55490437e-05 -3.01366076e-03 -1.59982514e-02
  8.76632482e-02  6.43171603e-03  9.34906706e-01 -4.60700101e-03
  0.00000000e+00  5.82634844e-02  6.50211098e-03  8.44363853e-01
 -4.75411396e-03  0.00000000e+00  6.56924963e-01  6.64385319e-01
  6.87637269e-01  7.29554236e-01  7.95948982e-01  8.97820115e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] 0.07670492845773696 False {}
results for output!  [0.9999674128061256, 0.9999997160812075, 0.9999918749241694

[-1.42620830e-02  3.55490437e-05 -3.01366076e-03 -1.59982514e-02
  8.76632482e-02  6.43171603e-03  9.34906706e-01 -4.60700101e-03
  0.00000000e+00  5.82634844e-02  6.50211098e-03  8.44363853e-01
 -4.75411396e-03  0.00000000e+00  6.56924963e-01  6.64385319e-01
  6.87637269e-01  7.29554236e-01  7.95948982e-01  8.97820115e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] 0.10254684454450767 False {}
results for output!  [0.999949355118612, 0.9999995361821199, 0.999987269396581, 0.9999757791380579, 0.8684506390616882, 0.9999586950697614, 0.9999714869999676, 0.13282394902307537, 0.999849623426283, 0.8845180870390823, 0.2279867261622861, 0.9855831063429805, 0.999993712164075, 0.9973956850572232, 0.9818752131160406, 0.9921597886369904, 0.9999968945654794, 0.9999844531022659, 0.9936424180019934, 0.8086594491602461, 0.9896862701184566, 0.9673312252088071, 0.25698591520949776, 0.9999988042503323]
[-1.42620830e-02  3.55490437e-05 -3.01366076e-03 -1.59982514e-02
  8.76632482e-0

[-1.42664015e-02  6.09147013e-06 -5.16419560e-04 -1.59996986e-02
  8.73471051e-02  1.10212318e-03  9.34906796e-01 -7.89427509e-04
  0.00000000e+00  5.76926433e-02  1.11421547e-03  8.45064878e-01
 -8.14689867e-04  0.00000000e+00  6.56926751e-01  6.64387107e-01
  6.87639117e-01  7.29556203e-01  7.95951128e-01  8.97822559e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] -0.0415948475909718 False {}
results for output!  [0.9999243627443366, 0.9999992746911743, 0.9999808438041393, 0.9999637748412329, 0.8319023119298374, 0.9999386343405936, 0.9999571408115293, 0.12968119047194837, 0.9997784504013494, 0.8517039528292729, 0.21018664974562506, 0.9800123593698844, 0.9999904259250592, 0.996294417287809, 0.974996438649433, 0.9890626516916841, 0.9999952305206627, 0.9999766399398475, 0.9910520787739345, 0.763177537531732, 0.9855995272710927, 0.9558463031297726, 0.23401223704193952, 0.9999981440989996]
[-1.42664015e-02  6.09147013e-06 -5.16419560e-04 -1.59996986e-02
  8.73471051e

[-1.42664015e-02  6.09147013e-06 -5.16419560e-04 -1.59996986e-02
  8.73471051e-02  1.10212318e-03  9.34906796e-01 -7.89427509e-04
  0.00000000e+00  5.76926433e-02  1.11421547e-03  8.45064878e-01
 -8.14689867e-04  0.00000000e+00  6.56926751e-01  6.64387107e-01
  6.87639117e-01  7.29556203e-01  7.95951128e-01  8.97822559e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] -0.02723211980859202 False {}
results for output!  [0.99988210346391, 0.9999988005230622, 0.9999698511357142, 0.9999434314242692, 0.7841258885635247, 0.9999049916016682, 0.9999326381685423, 0.10813713907462685, 0.9996606645379027, 0.8085605458609764, 0.17699289931296613, 0.9716953840651146, 0.9999847008889804, 0.9945736981184095, 0.9648169089539338, 0.9843866063978122, 0.9999922932852152, 0.9999633034840767, 0.9870806392589073, 0.7061432620401622, 0.979421356892882, 0.9394539921825493, 0.1962858229104978, 0.9999969603190029]
[-1.42664015e-02  6.09147013e-06 -5.16419560e-04 -1.59996986e-02
  8.73471051e

[-1.42664015e-02  6.09147013e-06 -5.16419560e-04 -1.59996986e-02
  8.73471051e-02  1.10212318e-03  9.34906796e-01 -7.89427509e-04
  0.00000000e+00  5.76926433e-02  1.11421547e-03  8.45064878e-01
 -8.14689867e-04  0.00000000e+00  6.56926751e-01  6.64387107e-01
  6.87639117e-01  7.29556203e-01  7.95951128e-01  8.97822559e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] -0.017117151826620103 False {}
results for output!  [0.999845805737485, 0.9999983722756949, 0.9999603305282323, 0.9999259298823118, 0.7513912859131548, 0.999876261429675, 0.9999114417244899, 0.09573087088334131, 0.9995610161613804, 0.7787090784480157, 0.15820686750546065, 0.9651856085052499, 0.9999796778421768, 0.9931763275508332, 0.956910512875393, 0.9806860108692317, 0.9999896918105227, 0.9999517713855879, 0.9839031404467031, 0.6687503212645676, 0.9745349847439866, 0.9271012426885021, 0.17494267567348376, 0.9999958998260969]
[-1.42664015e-02  6.09147013e-06 -5.16419560e-04 -1.59996986e-02
  8.7347105

[-1.42664015e-02  6.09147013e-06 -5.16419560e-04 -1.59996986e-02
  8.73471051e-02  1.10212318e-03  9.34906796e-01 -7.89427509e-04
  0.00000000e+00  5.76926433e-02  1.11421547e-03  8.45064878e-01
 -8.14689867e-04  0.00000000e+00  6.56926751e-01  6.64387107e-01
  6.87639117e-01  7.29556203e-01  7.95951128e-01  8.97822559e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] -0.012139629423618313 False {}
results for output!  [0.9997590785152084, 0.9999972964144386, 0.9999373947727908, 0.9998840457830502, 0.6914391356489171, 0.999808003239447, 0.9998604384586858, 0.0813472384600582, 0.9993264517144056, 0.7232606014560725, 0.13380103042103864, 0.9510991108098104, 0.9999674203043973, 0.9900203312198406, 0.9399624075321411, 0.9725585003214066, 0.9999832834962432, 0.9999240337151449, 0.976846939039016, 0.6036974927626677, 0.9638301109073797, 0.9015360698876178, 0.1465254250518102, 0.9999932573546444]
[-1.42664015e-02  6.09147013e-06 -5.16419560e-04 -1.59996986e-02
  8.73471051

[-1.42664015e-02  6.09147013e-06 -5.16419560e-04 -1.59996986e-02
  8.73471051e-02  1.10212318e-03  9.34906796e-01 -7.89427509e-04
  0.00000000e+00  5.76926433e-02  1.11421547e-03  8.45064878e-01
 -8.14689867e-04  0.00000000e+00  6.56926751e-01  6.64387107e-01
  6.87639117e-01  7.29556203e-01  7.95951128e-01  8.97822559e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] 0.06912599434455471 False {}
results for output!  [0.99969599085318, 0.9999964792863549, 0.9999205915307556, 0.9998535352061138, 0.6581611322471668, 0.9997585911715647, 0.9998231109978692, 0.07730936924010123, 0.9991580175689023, 0.6920004349480062, 0.12485499439698922, 0.9417756909613968, 0.9999583402026799, 0.9878375321123862, 0.9288565175411356, 0.9670886491017361, 0.9999784977888089, 0.9999037401668323, 0.9720493379759338, 0.5693822877528019, 0.956653357452157, 0.8853755717101437, 0.13563689753562547, 0.9999912644376514]
[-1.42664015e-02  6.09147013e-06 -5.16419560e-04 -1.59996986e-02
  8.73471051e

[-1.42664015e-02  6.09147013e-06 -5.16419560e-04 -1.59996986e-02
  8.73471051e-02  1.10212318e-03  9.34906796e-01 -7.89427509e-04
  0.00000000e+00  5.76926433e-02  1.11421547e-03  8.45064878e-01
 -8.14689867e-04  0.00000000e+00  6.56926751e-01  6.64387107e-01
  6.87639117e-01  7.29556203e-01  7.95951128e-01  8.97822559e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] 0.10663162058591844 False {}
results for output!  [0.9996263042022269, 0.9999955558106934, 0.9999019614895817, 0.9998198073841265, 0.6283125433647585, 0.999704144209806, 0.9997817486828113, 0.07834826998056044, 0.9989732043700781, 0.6635263815039674, 0.1215836385126201, 0.9320835413786348, 0.9999482145801892, 0.9854928059758357, 0.9174025952581528, 0.9613189892903191, 0.9999731381196386, 0.9998812562949391, 0.966958983024798, 0.5399271561163186, 0.949119301737857, 0.8691505619287123, 0.13073446183413706, 0.9999890207034052]
[-1.42664015e-02  6.09147013e-06 -5.16419560e-04 -1.59996986e-02
  8.73471051e-

[-1.42664015e-02  6.09147013e-06 -5.16419560e-04 -1.59996986e-02
  8.73471051e-02  1.10212318e-03  9.34906796e-01 -7.89427509e-04
  0.00000000e+00  5.76926433e-02  1.11421547e-03  8.45064878e-01
 -8.14689867e-04  0.00000000e+00  6.56926751e-01  6.64387107e-01
  6.87639117e-01  7.29556203e-01  7.95951128e-01  8.97822559e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] 0.13194052505493167 False {}
results for output!  [0.999539743919857, 0.9999943845707544, 0.9998787409295002, 0.9997778823631469, 0.5984413475741797, 0.9996366638469334, 0.9997302218824946, 0.0831000947063667, 0.9987450581117541, 0.6345821453753953, 0.1221239195040642, 0.9207827789435843, 0.9999355273253778, 0.9826590151273331, 0.9041628245737683, 0.9544801899833621, 0.9999663963042971, 0.999853250462069, 0.9608893491556327, 0.5116807165396511, 0.9402403519087683, 0.85092235905162, 0.12974393324407263, 0.9999861848012255]
[-1.42664015e-02  6.09147013e-06 -5.16419560e-04 -1.59996986e-02
  8.73471051e-02

[-1.42664015e-02  6.09147013e-06 -5.16419560e-04 -1.59996986e-02
  8.73471051e-02  1.10212318e-03  9.34906796e-01 -7.89427509e-04
  0.00000000e+00  5.76926433e-02  1.11421547e-03  8.45064878e-01
 -8.14689867e-04  0.00000000e+00  6.56926751e-01  6.64387107e-01
  6.87639117e-01  7.29556203e-01  7.95951128e-01  8.97822559e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] 0.18576602478821952 False {}
results for output!  [0.9993546448526245, 0.9999918102528065, 0.9998288575554237, 0.9996881396797392, 0.551745072997232, 0.9994927846764563, 0.9996196110469673, 0.09665631149411791, 0.998261253065599, 0.5883723890498584, 0.129309613280844, 0.8988359263904813, 0.9999080822133588, 0.9768342171253657, 0.8787931130715272, 0.9408428071273096, 0.9999517374619238, 0.9997931388695231, 0.948678999165119, 0.46990484173219116, 0.9227065362259912, 0.8174464178029399, 0.13471984617311117, 0.9999799797826496]
[-1.42664015e-02  6.09147013e-06 -5.16419560e-04 -1.59996986e-02
  8.73471051e-

results for output!  [0.9990951634965857, 0.9999879635523921, 0.9997581559892084, 0.9995620500101856, 0.5022190686606507, 0.9992925882038237, 0.9994630934189412, 0.09530073893935476, 0.9975967393229257, 0.5396742376638004, 0.12287339732639846, 0.8726079808174965, 0.9998685318839149, 0.9693337901593582, 0.8489166010084765, 0.9241057714232144, 0.9999303596975919, 0.999708117280568, 0.9334307369397736, 0.4249704595565058, 0.9013238013330829, 0.7798606365335552, 0.12619189047237844, 0.9999708006019083]
[-1.42743252e-02 -2.75111524e-05  1.02067709e-03 -1.59951544e-02
  8.71660337e-02 -1.10309792e-03  9.34906855e-01  0.00000000e+00
  0.00000000e+00  5.74028008e-02 -1.10011571e-03  8.45352098e-01
 -6.20881716e-10  0.00000000e+00  6.56928003e-01  6.64388418e-01
  6.87640429e-01  7.29557633e-01  7.95952618e-01  8.97824228e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] -0.07739287817043444 False {}
results for output!  [0.9990689795381451, 0.999987558602754, 0.999750968776

[-1.42743252e-02 -2.75111524e-05  1.02067709e-03 -1.59951544e-02
  8.71660337e-02 -1.10309792e-03  9.34906855e-01  0.00000000e+00
  0.00000000e+00  5.74028008e-02 -1.10011571e-03  8.45352098e-01
 -6.20881716e-10  0.00000000e+00  6.56928003e-01  6.64388418e-01
  6.87640429e-01  7.29557633e-01  7.95952618e-01  8.97824228e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] -0.13708268471559126 False {}
results for output!  [0.9987094528476543, 0.9999817258322448, 0.9996514661129943, 0.9993740533675781, 0.4420575697687703, 0.998998085083945, 0.9992274227397866, 0.07048377380208626, 0.9966363509870713, 0.48172772331820246, 0.0938380442837683, 0.840186673977459, 0.9998074746825809, 0.9593626985046986, 0.8124154101386261, 0.9030158121056571, 0.9998968163934447, 0.9995801841350602, 0.9138000239038797, 0.3679716088465874, 0.8744087440678732, 0.7356877558984796, 0.09482078724096388, 0.9999561163849158]
[-1.42743252e-02 -2.75111524e-05  1.02067709e-03 -1.59951544e-02
  8.7166033

[-1.42743252e-02 -2.75111524e-05  1.02067709e-03 -1.59951544e-02
  8.71660337e-02 -1.10309792e-03  9.34906855e-01  0.00000000e+00
  0.00000000e+00  5.74028008e-02 -1.10011571e-03  8.45352098e-01
 -6.20881716e-10  0.00000000e+00  6.56928003e-01  6.64388418e-01
  6.87640429e-01  7.29557633e-01  7.95952618e-01  8.97824228e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] -0.10935497787842913 False {}
results for output!  [0.9978254992395736, 0.9999662906906661, 0.9994037244389018, 0.998941929926513, 0.3588870389372887, 0.9983286855858204, 0.9986813506081755, 0.04595224200331538, 0.9944875108054629, 0.4001271315028967, 0.0635661132218055, 0.7813621106957795, 0.9996629049000394, 0.9389016254639673, 0.747765926924024, 0.8627163634014279, 0.9998162513459117, 0.9992838369177242, 0.8755319850815513, 0.29264963616633755, 0.823967266855322, 0.6626014518459806, 0.06151561076172629, 0.9999202293126426]
[-1.42743252e-02 -2.75111524e-05  1.02067709e-03 -1.59951544e-02
  8.71660337

[-1.42743252e-02 -2.75111524e-05  1.02067709e-03 -1.59951544e-02
  8.71660337e-02 -1.10309792e-03  9.34906855e-01  0.00000000e+00
  0.00000000e+00  5.74028008e-02 -1.10011571e-03  8.45352098e-01
 -6.20881716e-10  0.00000000e+00  6.56928003e-01  6.64388418e-01
  6.87640429e-01  7.29557633e-01  7.95952618e-01  8.97824228e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] 0.14929769881566246 False {}
results for output!  [0.9966300639750516, 0.9999435188628198, 0.9990634756395089, 0.9983553666132707, 0.29368849363732585, 0.9974317585400114, 0.9979333625237781, 0.029663356039441258, 0.9916627112767309, 0.33531131846501094, 0.04302657304399893, 0.7218491105002154, 0.9994599060124869, 0.9148079098408586, 0.6841120600874648, 0.8193171969609758, 0.9997012878716209, 0.9988779737516604, 0.8333487767690047, 0.23539411727146176, 0.7709750466045673, 0.5956233280583096, 0.03870263786170636, 0.9998680126202115]
[-1.42743252e-02 -2.75111524e-05  1.02067709e-03 -1.59951544e-02
  8.71

[-1.42743252e-02 -2.75111524e-05  1.02067709e-03 -1.59951544e-02
  8.71660337e-02 -1.10309792e-03  9.34906855e-01  0.00000000e+00
  0.00000000e+00  5.74028008e-02 -1.10011571e-03  8.45352098e-01
 -6.20881716e-10  0.00000000e+00  6.56928003e-01  6.64388418e-01
  6.87640429e-01  7.29557633e-01  7.95952618e-01  8.97824228e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] 0.0031823752820491734 False {}
results for output!  [0.9961339302532528, 0.999934140044729, 0.9989223161928045, 0.9981116471645946, 0.28578946537782723, 0.9970583828640425, 0.9976232802709202, 0.041100347532532666, 0.9904888075233573, 0.3257717645282121, 0.05341407242105012, 0.7024785253353414, 0.9993759523603492, 0.9053168339827786, 0.6642697473975365, 0.8035738994225894, 0.9996538252370155, 0.9987095387369902, 0.8179545728710083, 0.231481381666103, 0.7528084918919231, 0.5768535153726497, 0.04892951515117194, 0.9998464895238368]
[-1.42743252e-02 -2.75111524e-05  1.02067709e-03 -1.59951544e-02
  8.7166

[-1.42743252e-02 -2.75111524e-05  1.02067709e-03 -1.59951544e-02
  8.71660337e-02 -1.10309792e-03  9.34906855e-01  0.00000000e+00
  0.00000000e+00  5.74028008e-02 -1.10011571e-03  8.45352098e-01
 -6.20881716e-10  0.00000000e+00  6.56928003e-01  6.64388418e-01
  6.87640429e-01  7.29557633e-01  7.95952618e-01  8.97824228e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] -0.20746750804254047 False {}
results for output!  [0.9946975093996173, 0.9999039443200093, 0.9985059199409536, 0.9974034569977976, 0.23847562113807186, 0.9959916823053605, 0.9967109978657753, 0.025698912003812913, 0.9872076511919861, 0.278925218406898, 0.035233936806510435, 0.652122619175826, 0.9991212134734857, 0.8810320504156608, 0.6118033259766307, 0.7643156946102452, 0.9995069249699633, 0.9982144503697465, 0.7787801248825559, 0.18975359070457443, 0.7061848729738178, 0.5250451345979108, 0.029049399424710298, 0.9997783032991112]
[-1.42743252e-02 -2.75111524e-05  1.02067709e-03 -1.59951544e-02
  8.71

[-1.42743252e-02 -2.75111524e-05  1.02067709e-03 -1.59951544e-02
  8.71660337e-02 -1.10309792e-03  9.34906855e-01  0.00000000e+00
  0.00000000e+00  5.74028008e-02 -1.10011571e-03  8.45352098e-01
 -6.20881716e-10  0.00000000e+00  6.56928003e-01  6.64388418e-01
  6.87640429e-01  7.29557633e-01  7.95952618e-01  8.97824228e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] -0.1771498479048423 False {}
results for output!  [0.993024153121324, 0.9998665550865238, 0.9980151576763125, 0.9965757081311506, 0.19986443867479187, 0.9947563732703226, 0.9956383184302702, 0.014025208256638333, 0.9834657419203947, 0.24048068647477372, 0.021325565484290543, 0.6054325084819512, 0.9988163469299398, 0.8558161047855453, 0.5639541133334913, 0.7262572116720931, 0.9993291495024443, 0.9976321099422483, 0.7402547126414321, 0.15613368050951415, 0.6618901924717591, 0.47956793126424135, 0.013758392372164474, 0.9996946725072504]
[-1.42743252e-02 -2.75111524e-05  1.02067709e-03 -1.59951544e-02
  8.

[-1.42743252e-02 -2.75111524e-05  1.02067709e-03 -1.59951544e-02
  8.71660337e-02 -1.10309792e-03  9.34906855e-01  0.00000000e+00
  0.00000000e+00  5.74028008e-02 -1.10011571e-03  8.45352098e-01
 -6.20881716e-10  0.00000000e+00  6.56928003e-01  6.64388418e-01
  6.87640429e-01  7.29557633e-01  7.95952618e-01  8.97824228e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] -0.32265543683369835 False {}
results for output!  [0.9903277280680474, 0.9998017765923071, 0.9972131352696161, 0.9952364465634169, 0.1531910701354111, 0.9927798683769804, 0.9938903769894585, -0.9979831808569698, 0.9775889637562696, 0.19420529567037814, 0.0027087653568000913, 0.5460159292322917, 0.9983089394375801, 0.8202305378075061, 0.5038095281746913, 0.6760764690876697, 0.9990293361442293, 0.9966827165622036, 0.6887030909976473, 0.11525052027631988, 0.6043932313350306, 0.42394891023984416, 0.0003067822264304354, 0.9995513860529079]
[-1.42743252e-02 -2.75111524e-05  1.02067709e-03 -1.59951544e-02
  

[-1.42601244e-02  4.85516386e-05 -4.11597043e-03 -1.59976125e-02
  8.78024995e-02  8.78424477e-03  9.34906892e-01 -6.29209168e-03
  0.00000000e+00  5.85163943e-02  8.88042990e-03  8.44051674e-01
 -6.49309593e-03  0.00000000e+00  6.56923950e-01  6.64384305e-01
  6.87636256e-01  7.29553163e-01  7.95947790e-01  8.97818744e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] -0.27949615205824374 False {}
results for output!  [-0.5118819377245462, 0.3411679183811056, -0.9555707143228469, -0.8128128360628907, -0.15994718019706808, -0.749945266807968, -0.5862629706530796, -0.42193384955831814, -0.42359093228478323, -0.19828857401860017, -0.3692464026458561, -0.17135514735086121, -0.9437992961840534, -0.22596876168714886, -0.17140510235182035, -0.2346655970006819, 0.02972570397107477, -0.8962551200954271, -0.17713866469934367, -0.18618849267909177, -0.16802378714361968, -0.23258950691459274, -0.3296935097177009, 0.1919234059515864]
[-1.42601244e-02  4.85516386e-05 -4.11597043e

[-1.42601244e-02  4.85516386e-05 -4.11597043e-03 -1.59976125e-02
  8.78024995e-02  8.78424477e-03  9.34906892e-01 -6.29209168e-03
  0.00000000e+00  5.85163943e-02  8.88042990e-03  8.44051674e-01
 -6.49309593e-03  0.00000000e+00  6.56923950e-01  6.64384305e-01
  6.87636256e-01  7.29553163e-01  7.95947790e-01  8.97818744e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] -0.029326523686446365 False {}
results for output!  [-0.47188927363432487, 0.20920103979701965, -0.9268791133703931, -0.780232805147216, -0.15647944310318018, -0.7192941242878349, -0.5424917594506266, -0.44338499244973173, -0.39183013813321854, -0.19597074000015002, -0.38452212480352466, -0.16345058975575888, -0.9046446416391364, -0.2119135233012867, -0.16411899273235211, -0.22544106085979024, -0.9727528048156924, -0.8648650669483086, -0.16677267362396386, -0.18423802988232443, -0.15917309367328625, -0.22855339359798216, -0.3404774245497257, 0.06791260702132029]
[-1.42601244e-02  4.85516386e-05 -4.1159

[-1.42601244e-02  4.85516386e-05 -4.11597043e-03 -1.59976125e-02
  8.78024995e-02  8.78424477e-03  9.34906892e-01 -6.29209168e-03
  0.00000000e+00  5.85163943e-02  8.88042990e-03  8.44051674e-01
 -6.49309593e-03  0.00000000e+00  6.56923950e-01  6.64384305e-01
  6.87636256e-01  7.29553163e-01  7.95947790e-01  8.97818744e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] -0.004726306796073918 False {}
results for output!  [-0.6465609134257598, 0.4015943259854684, 0.10242965025559414, -0.988916817166123, -0.1782051067696188, -0.9405374988709138, -0.7454925074781378, -0.48548905202631915, -0.5254441175604853, -0.22151594345618178, -0.4212632118569909, -0.1946897560784157, 0.09742450683758608, -0.2644013530415404, -0.19418551694040034, -0.2699528026342824, 0.17297418198052839, 0.04207207009491176, -0.20369441131884225, -0.20750841462716557, -0.19174482099912396, -0.2628436621120173, -0.37464281903243996, 0.2680179182054683]
[-1.42601244e-02  4.85516386e-05 -4.11597043e-03

[-1.42601244e-02  4.85516386e-05 -4.11597043e-03 -1.59976125e-02
  8.78024995e-02  8.78424477e-03  9.34906892e-01 -6.29209168e-03
  0.00000000e+00  5.85163943e-02  8.88042990e-03  8.44051674e-01
 -6.49309593e-03  0.00000000e+00  6.56923950e-01  6.64384305e-01
  6.87636256e-01  7.29553163e-01  7.95947790e-01  8.97818744e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] -0.043159434378147135 False {}
results for output!  [-0.607781193289908, 0.25945048901576384, 0.0034339495151618493, -0.9484981773410364, -0.17366233070369053, -0.9039288048627069, -0.7059068234161926, -0.510981493640921, -0.4926760945669607, -0.21834906712340335, -0.43902222374340405, -0.18523181882467005, -0.9888449896307084, -0.24814530959549516, -0.18543367272002953, -0.2593797988200381, 0.04628115704674274, -0.9686551838002597, -0.19140673438129127, -0.2046753133586165, -0.18118384689400022, -0.25803987342870005, -0.38688740037705416, 0.12999131690135846]
[-1.42601244e-02  4.85516386e-05 -4.115970

[-1.42601244e-02  4.85516386e-05 -4.11597043e-03 -1.59976125e-02
  8.78024995e-02  8.78424477e-03  9.34906892e-01 -6.29209168e-03
  0.00000000e+00  5.85163943e-02  8.88042990e-03  8.44051674e-01
 -6.49309593e-03  0.00000000e+00  6.56923950e-01  6.64384305e-01
  6.87636256e-01  7.29553163e-01  7.95947790e-01  8.97818744e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] -0.03441189967887476 False {}
results for output!  [-0.8060789039401045, 0.36803182499615494, 0.10876607788182757, 0.0514028181543269, -0.19790100945118147, 0.005630756765806044, -0.9349385043893584, -0.5836785778233246, -0.6440296573952347, -0.24876671918991503, -0.4992335289571439, -0.2182103215939369, 0.10524345353977349, -0.3039748219681118, -0.21743402354803046, -0.30915222514606894, 0.16371293665888964, 0.07587192692187106, -0.22962249645841182, -0.23223787888937159, -0.21502543945068142, -0.2988896535538453, -0.43954718964330475, 0.24750450029526494]
[-1.42601244e-02  4.85516386e-05 -4.11597043e

results for output!  [-0.5060083628881669, -0.7618812024378796, -0.7018734411741391, -0.7026417831141235, -0.16016809607419583, -0.7175350981882263, -0.6054875398765377, -0.6219812034429713, -0.4041913426384085, -0.20975792422526743, -0.5159821024512893, -0.15728840490659657, -0.6648694402437151, -0.20154153777182926, -0.15947030804108375, -0.2286253231304897, -0.6660985671657913, -0.691790061013958, -0.15575431945278448, -0.19704034643431223, -0.1502391892008619, -0.244837362031127, -0.4402843492061657, -0.6802016677467366]
[-1.42601244e-02  4.85516386e-05 -4.11597043e-03 -1.59976125e-02
  8.78024995e-02  8.78424477e-03  9.34906892e-01 -6.29209168e-03
  0.00000000e+00  5.85163943e-02  8.88042990e-03  8.44051674e-01
 -6.49309593e-03  0.00000000e+00  6.56923950e-01  6.64384305e-01
  6.87636256e-01  7.29553163e-01  7.95947790e-01  8.97818744e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] -0.15465378991762913 False {}
results for output!  [-0.7275107675978403, 0.126

[-1.42601244e-02  4.85516386e-05 -4.11597043e-03 -1.59976125e-02
  8.78024995e-02  8.78424477e-03  9.34906892e-01 -6.29209168e-03
  0.00000000e+00  5.85163943e-02  8.88042990e-03  8.44051674e-01
 -6.49309593e-03  0.00000000e+00  6.56923950e-01  6.64384305e-01
  6.87636256e-01  7.29553163e-01  7.95947790e-01  8.97818744e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] -0.12134047897656995 False {}
results for output!  [-0.6791046348865356, 0.00719868293950765, -0.9291543389742117, -0.9161987651732326, -0.1815729335148222, -0.9231288439226782, -0.8102550376753082, -0.6793943900210839, -0.5338777276545648, -0.2363050124952683, -0.5639457796037988, -0.18654894888817788, -0.9026714118609589, -0.24975025593435587, -0.18792165449409493, -0.2725384521065997, -0.9182327602585456, -0.9139623150387518, -0.18921826776734227, -0.2209647331307922, -0.1801288475590406, -0.28086977888805686, -0.48263058856188207, -0.9464536604010274]
[-1.42601244e-02  4.85516386e-05 -4.11597043e-0

[-1.42606115e-02  4.58138110e-05 -3.88389185e-03 -1.59977436e-02
  8.77733678e-02  8.28893110e-03  9.34906632e-01 -5.93728696e-03
  0.00000000e+00  5.84621541e-02  8.37970525e-03  8.44120219e-01
 -6.12697378e-03  0.00000000e+00  6.56924129e-01  6.64384484e-01
  6.87636435e-01  7.29553342e-01  7.95947969e-01  8.97818983e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] -0.012056890577077865 False {}
results for output!  [0.41114617470125636, 0.7883248417518396, 0.6249000459860035, 0.584982040140464, -0.31598897579809193, 0.5594617965189597, 0.5142035058035397, -0.7817779292199439, 0.21099778419972348, -0.39323930253550005, -0.678771078432209, -0.3967252265377908, 0.6462055959312345, -0.5952365977878635, -0.38944076832943664, -0.5625610102051796, 0.6853935236424629, 0.606971716066818, -0.43917949288013974, -0.35836391701197334, -0.4006460398309493, -0.5004335762232891, -0.6016282370144658, 0.7353117250244077]
[-1.42606115e-02  4.58138110e-05 -3.88389185e-03 -1.5997743

[-1.42606115e-02  4.58138110e-05 -3.88389185e-03 -1.59977436e-02
  8.77733678e-02  8.28893110e-03  9.34906632e-01 -5.93728696e-03
  0.00000000e+00  5.84621541e-02  8.37970525e-03  8.44120219e-01
 -6.12697378e-03  0.00000000e+00  6.56924129e-01  6.64384484e-01
  6.87636435e-01  7.29553342e-01  7.95947969e-01  8.97818983e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] -0.032907999083399773 False {}
results for output!  [0.3494925252901111, 0.7373902224694302, 0.5656106857639114, 0.5251719778564059, -0.31665999635005, 0.5008277513972132, 0.45273810868293096, -0.8241798122708313, 0.16162963327515278, -0.397928464621836, -0.7117334081345474, -0.39374198879175065, 0.5845089194151196, -0.591140983076306, -0.3871933089645524, -0.5649926133475687, 0.6247930547758058, 0.5469041096163763, -0.43365245859342333, -0.3621838634661361, -0.39616183589282267, -0.5073646149447815, -0.6270636974485043, 0.677901695930075]
[-1.42606115e-02  4.58138110e-05 -3.88389185e-03 -1.59977436e-0

[-1.42606115e-02  4.58138110e-05 -3.88389185e-03 -1.59977436e-02
  8.77733678e-02  8.28893110e-03  9.34906632e-01 -5.93728696e-03
  0.00000000e+00  5.84621541e-02  8.37970525e-03  8.44120219e-01
 -6.12697378e-03  0.00000000e+00  6.56924129e-01  6.64384484e-01
  6.87636435e-01  7.29553342e-01  7.95947969e-01  8.97818983e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] -0.03818548738956452 False {}
results for output!  [0.7233127984510521, 0.9380816616663483, 0.8449381602863024, 0.8165664661726273, -0.48342757056678987, 0.793903315727938, 0.7847265191162254, -0.8899377017545226, 0.5888321534219552, -0.5834667321004242, -0.8019770325493848, -0.6707197546823326, 0.8647266330993901, 0.000604286321909786, -0.6509845241588754, -0.906144279108184, 0.8883444750308445, 0.8342542324813931, -0.765890347337042, -0.5237247307059157, -0.6914716499917746, -0.7625654209394982, -0.7280877129248327, 0.9149745874710518]
[-1.42606115e-02  4.58138110e-05 -3.88389185e-03 -1.59977436e-02


[-1.42606115e-02  4.58138110e-05 -3.88389185e-03 -1.59977436e-02
  8.77733678e-02  8.28893110e-03  9.34906632e-01 -5.93728696e-03
  0.00000000e+00  5.84621541e-02  8.37970525e-03  8.44120219e-01
 -6.12697378e-03  0.00000000e+00  6.56924129e-01  6.64384484e-01
  6.87636435e-01  7.29553342e-01  7.95947969e-01  8.97818983e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] 0.09327216771245002 False {}
results for output!  [0.8314661774866126, 0.9717865633649307, 0.9127608122605502, 0.8924414749292062, -0.6150582587777347, 0.8747381681414448, 0.8732914505227525, -0.9463181391215626, 0.7316156499975288, -0.7259779353406516, -0.8733277721222329, -0.883958956357459, 0.9275685558873124, 0.21732888251082305, -0.8550450033363262, 0.0991445158972557, 0.942889191507376, 0.9056129457717463, 0.0040168354618395075, -0.6486755781041479, -0.9179773667232863, -0.9496645844449223, -0.8056461445232466, 0.9590569695194928]
[-1.42606115e-02  4.58138110e-05 -3.88389185e-03 -1.59977436e-02
 

[-1.42606115e-02  4.58138110e-05 -3.88389185e-03 -1.59977436e-02
  8.77733678e-02  8.28893110e-03  9.34906632e-01 -5.93728696e-03
  0.00000000e+00  5.84621541e-02  8.37970525e-03  8.44120219e-01
 -6.12697378e-03  0.00000000e+00  6.56924129e-01  6.64384484e-01
  6.87636435e-01  7.29553342e-01  7.95947969e-01  8.97818983e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] -0.1129181069433689 False {}
results for output!  [0.8126174924291196, 0.9672879812016115, 0.9017536185878583, 0.8794919031226267, -0.6407376583123917, 0.8604787986176403, 0.8576738321178587, -0.9929341573306409, 0.7079725520094045, -0.7593563348987499, -0.9166563836051783, -0.9211721165441475, 0.9176172435551395, 0.20225845151518818, -0.8914849828835085, 0.0932106362425511, 0.9345791016116425, 0.8938532478027676, -0.9996794522169028, -0.6773049248240745, -0.9556157267427405, -0.9938947724007988, -0.8445544678078961, 0.9527334318944483]
[-1.42606115e-02  4.58138110e-05 -3.88389185e-03 -1.59977436e-02
 

[-1.42606115e-02  4.58138110e-05 -3.88389185e-03 -1.59977436e-02
  8.77733678e-02  8.28893110e-03  9.34906632e-01 -5.93728696e-03
  0.00000000e+00  5.84621541e-02  8.37970525e-03  8.44120219e-01
 -6.12697378e-03  0.00000000e+00  6.56924129e-01  6.64384484e-01
  6.87636435e-01  7.29553342e-01  7.95947969e-01  8.97818983e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] -0.21888524278005206 False {}
results for output!  [-0.2358217584171884, -0.2300783270907773, -0.3108307627895737, -0.3218731342305954, -0.1800861946561539, -0.3483291886523448, -0.25559723523510786, -0.9128279572367155, -0.2209579335070993, -0.25653787047868654, -0.7542237612536703, -0.1713267078227919, -0.26022887025587466, -0.16530500498793504, -0.1756783505375919, -0.22228211870510253, -0.24271470516818297, -0.30717008715567784, -0.1459268914369922, -0.23468219859375974, -0.15935278711849293, -0.3091598114597614, -0.6190543148781815, -0.22661060994145102]
[-1.42606115e-02  4.58138110e-05 -3.8838918

[-1.42606115e-02  4.58138110e-05 -3.88389185e-03 -1.59977436e-02
  8.77733678e-02  8.28893110e-03  9.34906632e-01 -5.93728696e-03
  0.00000000e+00  5.84621541e-02  8.37970525e-03  8.44120219e-01
 -6.12697378e-03  0.00000000e+00  6.56924129e-01  6.64384484e-01
  6.87636435e-01  7.29553342e-01  7.95947969e-01  8.97818983e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] -0.1412022201021536 False {}
results for output!  [0.7480945375439008, 0.9486439386985861, 0.8626643652197739, 0.8346405803927042, -0.6802153538341444, 0.8126209792466179, 0.8021163569467413, 0.039838447057598536, 0.6350416122551301, -0.8183946502020394, 0.006529699404680844, -0.9701672667583163, 0.8802540709082181, 0.1726061584764671, -0.9412254791770456, 0.09925039059258745, 0.9022195445622929, 0.8523281612686897, 0.005680731333432831, -0.7266731029536859, 0.0014795919528636237, 0.03248095432726861, -0.9285485224956262, 0.9271023840431494]
[-1.42606115e-02  4.58138110e-05 -3.88389185e-03 -1.59977436e

[-1.42606115e-02  4.58138110e-05 -3.88389185e-03 -1.59977436e-02
  8.77733678e-02  8.28893110e-03  9.34906632e-01 -5.93728696e-03
  0.00000000e+00  5.84621541e-02  8.37970525e-03  8.44120219e-01
 -6.12697378e-03  0.00000000e+00  6.56924129e-01  6.64384484e-01
  6.87636435e-01  7.29553342e-01  7.95947969e-01  8.97818983e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] 0.03665481893221657 False {}
results for output!  [0.705594443499928, 0.9345374863585805, 0.834969940897168, 0.8033293413998306, -0.726892999663008, 0.7795622633800001, 0.7640992044010206, 0.04436166914848805, 0.589136879221233, -0.8795769707970017, 0.020262840062331255, 0.001825558893046031, 0.8534262094673801, 0.154295168362254, 0.003236245509252056, 0.09681444240275461, 0.8785853911313859, 0.8230864187805818, 0.0031210587120589217, -0.779568659602243, 0.00042229886162470365, 0.040018185937517936, 0.00018077307507269325, 0.908002922519102]
[-1.42606115e-02  4.58138110e-05 -3.88389185e-03 -1.59977436e

[-1.42606115e-02  4.58138110e-05 -3.88389185e-03 -1.59977436e-02
  8.77733678e-02  8.28893110e-03  9.34906632e-01 -5.93728696e-03
  0.00000000e+00  5.84621541e-02  8.37970525e-03  8.44120219e-01
 -6.12697378e-03  0.00000000e+00  6.56924129e-01  6.64384484e-01
  6.87636435e-01  7.29553342e-01  7.95947969e-01  8.97818983e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] -0.09280017145474632 False {}
results for output!  [-0.4285703934914937, -0.5286070946676105, -0.5678982611645922, -0.5667010774476214, -0.3190460992319055, -0.589695635276231, -0.46622643494804566, -0.9934124024081827, -0.3960878401794744, -0.44859714795868233, -0.8967716664231069, -0.3331963015596414, -0.5080404908319639, -0.303700599603402, -0.3499247081004187, -0.3807797117651779, -0.49654734096752656, -0.5574243942716701, -0.27507967057668825, -0.39812399354886086, -0.30365195419909713, -0.4772910688288865, -0.8228325753172736, -0.4926439279929392]
[-1.42606115e-02  4.58138110e-05 -3.88389185e-03 

[-1.42588541e-02  5.55035379e-05 -4.70535815e-03 -1.59972680e-02
  8.78763199e-02  1.00421123e-02  9.34906840e-01 -7.19309909e-03
  0.00000000e+00  5.86512722e-02  1.01520661e-02  8.43884274e-01
 -7.42286071e-03  0.00000000e+00  6.56923413e-01  6.64383769e-01
  6.87635660e-01  7.29552567e-01  7.95947134e-01  8.97818029e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] -0.24100591489672663 False {}
results for output!  [0.16217949243044005, 0.5842382331165357, 0.40654580517725436, 0.3579557442634478, -0.5937102157246071, 0.33857775290237835, 0.24459058267784184, 0.021914077764587425, 0.051863661111825055, -0.7684115718083034, -0.9818678656716123, -0.7140937851435886, 0.40156711122545086, -0.7599863686162492, -0.72499144520067, -0.7942985915291858, 0.4395569546536595, 0.38285473591610675, -0.6692848323959647, -0.6745701744173178, -0.6906067163388003, -0.8281726819998534, -0.9512959959076108, 0.4988967359750416]
[-1.42588541e-02  5.55035379e-05 -4.70535815e-03 -1.59972

[-1.42588541e-02  5.55035379e-05 -4.70535815e-03 -1.59972680e-02
  8.78763199e-02  1.00421123e-02  9.34906840e-01 -7.19309909e-03
  0.00000000e+00  5.86512722e-02  1.01520661e-02  8.43884274e-01
 -7.42286071e-03  0.00000000e+00  6.56923413e-01  6.64383769e-01
  6.87635660e-01  7.29552567e-01  7.95947134e-01  8.97818029e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] -0.36434028760592263 False {}
results for output!  [0.37033498111338403, 0.7537737667225559, 0.5871046655281933, 0.5423820102623029, -0.7367706227847861, 0.5184841139334868, 0.44672492508706285, 0.037326597722828314, 0.25776627739717317, -0.9283652218886526, 0.017775414591185035, -0.8925166303252541, 0.5934465067704573, -0.9618926538329265, -0.8993706405103695, -0.9754280232818879, 0.631095512524986, 0.566809917186077, -0.8611326796801572, -0.8165061733024327, -0.8747307358886963, -0.981224782802441, 0.0029661507721250313, 0.6858108106226979]
[-1.42588541e-02  5.55035379e-05 -4.70535815e-03 -1.59972680

[-1.42588541e-02  5.55035379e-05 -4.70535815e-03 -1.59972680e-02
  8.78763199e-02  1.00421123e-02  9.34906840e-01 -7.19309909e-03
  0.00000000e+00  5.86512722e-02  1.01520661e-02  8.43884274e-01
 -7.42286071e-03  0.00000000e+00  6.56923413e-01  6.64383769e-01
  6.87635660e-01  7.29552567e-01  7.95947134e-01  8.97818029e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] -0.18142666888237002 False {}
results for output!  [0.3371163375832198, 0.7273016197723723, 0.5596538993339795, 0.5144762346980991, -0.7530457462673412, 0.4919334410608349, 0.41207055568587214, 0.03691267984200164, 0.23019917749981733, -0.9455927733362289, 0.023272451982962128, -0.9014828805148811, 0.5618436945294509, -0.9664358837567703, -0.9092930269282302, -0.9879990557198656, 0.5989722611453447, 0.5387240068536594, -0.8667934050672917, -0.8370082016792639, -0.8817533053419133, -0.9999735054264457, 0.009115620988294104, 0.6547773922933386]
[-1.42588541e-02  5.55035379e-05 -4.70535815e-03 -1.59972680

[-1.42588541e-02  5.55035379e-05 -4.70535815e-03 -1.59972680e-02
  8.78763199e-02  1.00421123e-02  9.34906840e-01 -7.19309909e-03
  0.00000000e+00  5.86512722e-02  1.01520661e-02  8.43884274e-01
 -7.42286071e-03  0.00000000e+00  6.56923413e-01  6.64383769e-01
  6.87635660e-01  7.29552567e-01  7.95947134e-01  8.97818029e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] -0.20749445296327393 False {}
results for output!  [-0.044524803716523356, -0.01891254920946135, -0.052746559737048476, -0.06064551106750804, -0.24404432176343172, -0.07492118151258283, -0.041813173983981045, 0.005592706696909255, -0.05778510580060918, -0.3855649200483461, -0.9283479713763817, -0.16672284421289538, -0.034214948181117005, -0.10509128282638681, -0.18521645486488697, -0.1929348688415935, -0.02696312708923973, -0.053244379589054154, -0.11174503996990792, -0.3467008931185125, -0.13744024302996874, -0.3368208229793742, -0.8330421807668067, -0.020761801947989277]
[-1.42588541e-02  5.55035379e

[-1.42588541e-02  5.55035379e-05 -4.70535815e-03 -1.59972680e-02
  8.78763199e-02  1.00421123e-02  9.34906840e-01 -7.19309909e-03
  0.00000000e+00  5.86512722e-02  1.01520661e-02  8.43884274e-01
 -7.42286071e-03  0.00000000e+00  6.56923413e-01  6.64383769e-01
  6.87635660e-01  7.29552567e-01  7.95947134e-01  8.97818029e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] 0.0037969520886727177 False {}
results for output!  [0.49608667528623496, 0.8301517398118021, 0.6832259797047076, 0.6391861678737591, -0.8603094895419029, 0.6149794916218239, 0.5582184467109652, 0.0588241418343165, 0.3961842761641199, 0.03742053387647504, 0.06658223757267723, 0.023068905932914552, 0.6917075229886207, 0.11454988070937877, 0.027242890873417025, 0.1161224367244893, 0.7258107819071797, 0.6647439494122866, 0.002378149325140244, -0.9421524534619987, 0.008976265232188307, 0.10384497431338002, 0.06660574646676021, 0.7740396192617769]
[-1.42588541e-02  5.55035379e-05 -4.70535815e-03 -1.59972680

[-1.42588541e-02  5.55035379e-05 -4.70535815e-03 -1.59972680e-02
  8.78763199e-02  1.00421123e-02  9.34906840e-01 -7.19309909e-03
  0.00000000e+00  5.86512722e-02  1.01520661e-02  8.43884274e-01
 -7.42286071e-03  0.00000000e+00  6.56923413e-01  6.64383769e-01
  6.87635660e-01  7.29552567e-01  7.95947134e-01  8.97818029e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00] 0.0660730591416359 False {}
results for output!  [0.47279144122923644, 0.8133037301612458, 0.6632585182665913, 0.6184020505327377, -0.9122274023812933, 0.5947785583301415, 0.5332384187104064, 0.06748540352827925, 0.3781860389844407, 0.04763546294962717, 0.07421418156516202, 0.031644399532500644, 0.669396335838923, 0.11742862542763022, 0.03585952732098874, 0.12342174810920215, 0.7036232735895318, 0.6442367758884615, 0.011278076801247261, -0.9986167723437975, 0.01749292762245247, 0.11399279147092489, 0.07154864117567028, 0.7533696341561387]
[-1.42588541e-02  5.55035379e-05 -4.70535815e-03 -1.59972680e-02

TypeError: 'NoneType' object is not subscriptable

In [43]:
import random, math
random.seed(422142)

def mult_and_sum(a, b):
    result = 0
    for i in range(len(a)):
        result += a[i] * b[i]
    return result

def l_plus_c(a, c):
    result = []
    for i in range(len(a)):
        res = a[i] + c
        result.append(res)
    return result

class Marvin(object):
    def __init__(self, inputs_count):
        self.w = [random.random()] * inputs_count
        self.bias = random.random()
        
    def _net_input(self, data):
        return mult_and_sum(self.w, data) + self.bias
    
    def _activation_function(self, observation):
        net_input = self._net_input(observation)
        return 1 / (1 + math.exp(-(net_input)))
        
    # Returning 1 single number
    def predict(self, data):
        result = self._activation_function(data)
        return ((result - 0.5) * 2 if result >= 0.5 else (-result * 2))

    def accuracy(self, data, target):
        result = 0
        for X, y in zip(data, target):
            result += int(self.predict(X) == y)
        return result / len(target)    
    
    def learn(self, observation, action, reward, eta = 0.001):
        data = np.concatenate((observation, action), axis=None)
        e = eta * (reward - self.predict(data))
        self.w += data * e
        self.bias += e
        return

In [44]:
observation = env.reset()
action = env.action_space.sample()
print(type(observation), type(action))
print(action_space_size + state_space_size)

<class 'numpy.ndarray'> <class 'numpy.ndarray'>
28


In [58]:
robot = Marvin(action_space_size + state_space_size)

for j in range(50000):
    observation = env.reset()
    for i in range(20):
        action = env.action_space.sample()
        observation_new, reward, done, info = env.step(action)
    #     print(reward)
        if (reward <= 1 and reward >= -1):
            robot.learn(observation, action, reward, 0.0001)
        else:
            break
        observation = observation_new

observation = env.reset()
X = []
y = []
for k in range(10):
    action = env.action_space.sample()
    observation, reward, done, info = env.step(action)
    data = np.concatenate((observation, action), axis=None)
    X.append(data)
    y.append(reward)
    
#print(X)
#print(y)
print(robot.predict(X[0]), y[0])
print(robot.accuracy(X, y))


0.009307011625510508 -0.07481399103750666
0.0


In [59]:
for k in range(10):
    print(robot.predict(X[k]), y[k])

0.009307011625510508 -0.07481399103750666
0.007328073585658901 -0.11518605728447437
0.004950032265731208 -0.08263521004716674
0.005069243288558178 -0.08054902566472807
0.0027335650575319725 -0.1265358516275883
0.0014251222912342598 -0.20129821601510048
0.004863242205111584 0.01990209116538604
0.00527117037000302 0.07903253786265851
-0.9999082724839304 0.08354698637375993
0.006463804152735841 0.045246084546051814


In [ ]:
observation = env.reset()
for limb in robot:
    print(limb.predict(observation))

In [ ]:
state = env.reset()
print(state)


In [ ]:
num_episodes = 10
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [ ]:
rewards_all_episodes = []

#Q-learning algorithm
for episode in range(num_episodes):
    state = env.reset()
    
    done = False
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode):
        env.render()
        # Exploration-Explotation trade off
#         exploration_rate_treshold = random.uniform(0,1)
#         if exploration_rate_treshold >= exploration_rate:
#             action = np.argmax(q_table[state])
#         else:
#             action = env.action_space.sample()
        
#         print("action = ", action)
        action = []
        for limb in robot:
            action.append(limb.predict(observation))
        observation, reward, done, info = env.step(action)
#         print(observation, reward, done, info)
        # Update Q-table
#         q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
#             learning_rate * (reward  + discount_rate * np.max(q_table[state]))
#         state = observation
#         rewards_current_episode += reward
        if done == True or reward == -100:
            break
            
#     #Exploration decay logic 
#     exploration_rate = min_exploration_rate + \
#         (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)
#     rewards_all_episodes.append(rewards_current_episode)

# #Calculate and print the average reward per 1000 episodes
# rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes / 1000)
# count = 1000
# print("*** Average reward per 1000 episodes ***\n")
# for r in rewards_per_thousand_episodes:
#     print(count, ": ", str(sum(r/ 1000)))
#     count += 1000
    

# #Print updated Q-table
# print("\n\n*****Q-table*****\n\n")
# print(q_table)

In [ ]:
import random, math
random.seed(422142)

def mult_and_sum(a, b):
    result = 0
    for i in range(len(a)):
        result += a[i] * b[i]
    return result

class Marvin(object):
    def __init__(self, inputs_count):
        self.w = [random.random()] * inputs_count
        self.bias = random.random()
        
    def _net_input(self, observation):
        return mult_and_sum(self.w, observation) + self.bias
    
    def _activation_function(self, observation):
        net_input = self._net_input(observation)
        return 1 / (1 + math.exp(-(net_input)))
        
    def predict(self, data):
        result = self._activation_function(data)
        return ((result - 0.5) * 2 if result >= 0.5 else (-result * 2))

    def learn(self, observation, action, reward, eta = 0.001):
        e = reward - (self.predict(observation) - action)
        self.w = self.w + eta * e * observation
        self.bias = self.bias + eta * e
        return


    robot = [Marvin(24), Marvin(24), Marvin(24), Marvin(24)]

for j in range(7000):
    observation = env.reset()
    for i in range(100):
        action = env.action_space.sample()
        observation_new, reward, done, info = env.step(action)
    #     print(reward)
        if (reward <= 1 and reward >= -1):
            for index in range(len(robot)):
                robot[index].learn(observation, action[index], reward)
        else:
            break
        observation = observation_new
    
